site_name: Dokumentazioa
nav:
  - INICIO: index.md
  - LINKS O INFORMACIÓN: links.md
  - AIRFLOW: airflow.md
  - ALGORITMO GENETICO: GA.md
  - APACHE BEAM: beam.md
  - BIGQUERY: bigquery.md
  - DJANGO: django.md
  - GIT: git.md
  - PANDAS: pandas.md
  - PROPHET: prophet.md
  - STORAGE: storage.md
  - REDIS: redis.md
  - SIMPY: simpy.md
  - SQL: sql.md
  - STRAPI: strapi.md

theme: readthedocs